### ISSUE TITLE
Doesn't work on primevideo.com

### ISSUE THREAD

**Issue by Marconius6** [Coffee-fueled-deadlines/amazon_xray_shield#2]
This doesn't seem to work when viewing through https://www.primevideo.com
Reporting in case it's a simple fix.

**Comment by Coffee-fueled-deadlines** [comment]
What's the benefit of using primevideo.com over the regular Amazon site?  Just a url change?

**Comment by Coffee-fueled-deadlines** [comment]
@Marconius6 since none of our development team has access to primevideo.com, could  you do the following for us:

1. Tell us what country you're viewing from?
2. Send us the html source code of the page while you're viewing any video that has the xray feature up (control + u while the webpage and video are up and running)

Thank you, this will help us get this patched.

**Comment by Marconius6** [comment]
> What's the benefit of using primevideo.com over the regular Amazon site? Just a url change?

It's a separate subscription from Prime. You can be subscribed to just Prime Video, which is cheaper. I'm pretty sure the backend is all the same though.

>Tell us what country you're viewing from?

I'm viewing from Finland, though I believe the site is international. Content is still region-locked, but the site doesn't have country-specific urls like Amazon.

Code attached as a file
[primevideo.txt](https://github.com/user-attachments/files/18247661/primevideo.txt)

**Comment by kateykat** [comment]
@Marconius6 Could you open the inspect element of the video player (F12) and do a search for "xrayQuickView"? We're just trying to figure out whether or not that exists. It's not in the file you've attached.

**Comment by Marconius6** [comment]
> @Marconius6 Could you open the inspect element of the video player (F12) and do a search for "xrayQuickView"? We're just trying to figure out whether or not that exists. It's not in the file you've attached.

Yup, it's definitely there.
https://i.imgur.com/MEf91jA.png

Here's the tree to it, as best I could get it
https://i.imgur.com/m3A2Vqj.png

**Comment by Coffee-fueled-deadlines** [comment]
@Marconius6 : we've made the adjustments to include xrayQuickView from primevideo and submitted it to the Chrome Web Store so it should be live within the next few hours to next few days (depending on when chrome decides to approve it).  Please let us know if it works for you when it does eventually go live.  I appreciate the issue.

**Comment by Marconius6** [comment]
> @Marconius6 : we've made the adjustments to include xrayQuickView from primevideo and submitted it to the Chrome Web Store so it should be live within the next few hours to next few days (depending on when chrome decides to approve it). Please let us know if it works for you when it does eventually go live. I appreciate the issue.

Thank you for your quick response!

I am actually using Firefox, did you also update it there? Or could you update this ticket when the update goes live, and then I can test it?

**Comment by Coffee-fueled-deadlines** [comment]
> > @Marconius6 : we've made the adjustments to include xrayQuickView from primevideo and submitted it to the Chrome Web Store so it should be live within the next few hours to next few days (depending on when chrome decides to approve it). Please let us know if it works for you when it does eventually go live. I appreciate the issue.
> 
> Thank you for your quick response!
> 
> I am actually using Firefox, did you also update it there? Or could you update this ticket when the update goes live, and then I can test it?

Correct, we updated the mozilla extension as well, they have on their site that there are some delays though.  It's version 1.24 but I can also @ you when the update goes live.

**Comment by Marconius6** [comment]
It's updated to 1.24 in the Firefox store now.

Tested it, and it seems to work for me! Thanks for the quick update.

**Comment by Coffee-fueled-deadlines** [comment]
> It's updated to 1.24 in the Firefox store now.
> 
> Tested it, and it seems to work for me! Thanks for the quick update.

So much for a few days haha.  I'm glad that it's working!  Thank you for the help getting it working.  Is there anything else we can help with?

**Comment by Marconius6** [comment]
> > It's updated to 1.24 in the Firefox store now.
> > Tested it, and it seems to work for me! Thanks for the quick update.
> 
> So much for a few days haha. I'm glad that it's working! Thank you for the help getting it working. Is there anything else we can help with?

I'm good if it all seems to be working!
